#!/bin/sh
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

exec git diff-index --check --cached $against --

. "$(dirname "$0")/_/husky.sh"

npx lint-staged
